'use strict';
const menu=document.querySelector('.menu-toggle'),nav=document.querySelector('#main-nav');
menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));});
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false');}));
const search=document.querySelector('#symbol-search');search.addEventListener('input',()=>{let count=0;document.querySelectorAll('.symbol-card').forEach(card=>{card.hidden=!card.textContent.toLowerCase().includes(search.value.toLowerCase().trim());if(!card.hidden)count++;});document.querySelector('#symbol-status').textContent=count+' controls shown';});
const enquiry=document.querySelector('#enquiry-dialog');document.querySelectorAll('[data-enquiry]').forEach(b=>b.addEventListener('click',()=>enquiry.showModal()));document.querySelector('#close-enquiry').addEventListener('click',()=>enquiry.close());
function saveText(text,name,type='text/plain'){const u=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000);}
document.querySelector('#enquiry-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);saveText('CMM programming / inspection enquiry\n\nName: '+f.get('name')+'\nCompany: '+f.get('company')+'\nWork email: '+f.get('email')+'\n\nRequirement:\n'+f.get('requirement')+'\n\nThis is a draft, not a submitted enquiry. Share it through your approved company contact channel.','CMM-enquiry-draft.txt');document.querySelector('#enquiry-status').textContent='Draft downloaded. It has not been sent. Share it through your approved company contact channel.';});
document.querySelector('#sample-download').addEventListener('click',()=>saveText('EDUCATIONAL EXAMPLE ONLY - NOT A COMPANY INSPECTION REPORT\nUnits: mm; Deviation = Actual - Nominal\nCoordinate,Nominal,Actual,Deviation\nBL,100.000,100.040,+0.040\nTL,200.000,199.970,-0.030\nWL,50.000,50.020,+0.020\nNo acceptance decision is stated. These coordinate deviations are not a GD&T evaluation.','CMM-training-example.csv','text/csv'));
